version: "3.9"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: SupaSavePassword@
      POSTGRES_DB: DBCorebiz

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
